// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIIpq0dFy4vshBOULbwgGfJmREEb1iOPQ',
    appId: '1:674450367715:web:c718ea8b50345201a491d6',
    messagingSenderId: '674450367715',
    projectId: 'danfoss-1c3be',
    authDomain: 'danfoss-1c3be.firebaseapp.com',
    databaseURL: 'https://danfoss-1c3be-default-rtdb.firebaseio.com',
    storageBucket: 'danfoss-1c3be.appspot.com',
    measurementId: 'G-M6VX1WBPDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUGqFCd4j3hjSOXh5YeheVO_p4K7uE0Y',
    appId: '1:674450367715:android:b348bc83fddf145da491d6',
    messagingSenderId: '674450367715',
    projectId: 'danfoss-1c3be',
    databaseURL: 'https://danfoss-1c3be-default-rtdb.firebaseio.com',
    storageBucket: 'danfoss-1c3be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQd1XKCJbNidFnaBhZ3-n2HjRDgaBIFr8',
    appId: '1:674450367715:ios:e590a38adbd2eadba491d6',
    messagingSenderId: '674450367715',
    projectId: 'danfoss-1c3be',
    databaseURL: 'https://danfoss-1c3be-default-rtdb.firebaseio.com',
    storageBucket: 'danfoss-1c3be.appspot.com',
    iosClientId: '674450367715-qpikbum0lu7rluc69lcil6ujp31onna5.apps.googleusercontent.com',
    iosBundleId: 'com.example.danfoss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQd1XKCJbNidFnaBhZ3-n2HjRDgaBIFr8',
    appId: '1:674450367715:ios:fe4384380a72e2a0a491d6',
    messagingSenderId: '674450367715',
    projectId: 'danfoss-1c3be',
    databaseURL: 'https://danfoss-1c3be-default-rtdb.firebaseio.com',
    storageBucket: 'danfoss-1c3be.appspot.com',
    iosClientId: '674450367715-lm4o2thn3kdvcpni16bf6cf4q5oo2mfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.danfoss.RunnerTests',
  );
}
